
export const RESTAURANT_REQUEST = 'RESTAURANT_REQUEST';

export const RESTAURANT_ERROR = 'RESTAURANT_ERROR';

export const GET_RESTAURANT = 'GET_ALL_RESTAURANT';

export const ADD_RESTAURANT = 'ADD_RESTAURANT';

export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';

export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';